package com.alokrathava.sdk.model

data class RobotTelemetry(
    val poseValid: Boolean = false,
    val frame: String = "map",
    val xMeters: Double = 0.0,
    val yMeters: Double = 0.0,
    val yawRadians: Double = 0.0,
    val linearVelocityMps: Double = 0.0,
    val angularVelocityRadPerSec: Double = 0.0,
    val isMoving: Boolean = false,
    val navigationState: String = "IDLE",
    val distanceRemainingMeters: Float? = null,
    val navigationElapsedSeconds: Float = 0f,
    val hasGoal: Boolean = false,
    val navigationErrorCode: Int = 0,
    val navigationErrorMessage: String = "",
    val localizationState: String = "UNINITIALIZED",
    val localizationPositionStddevMeters: Float? = null,
    val localizationYawStddevRadians: Float? = null,
    val safetyState: SafetyState = SafetyState.NORMAL,
    val emergencyStopped: Boolean = false,
    val collisionStopped: Boolean = false,
    val controlSource: String = "none",
    val nearestObstacleDistanceMeters: Float? = null,
    val nearestObstacleBearingRadians: Float? = null,
    val dockingState: DockingState = DockingState.UNDOCKED,
    val isDocked: Boolean = false,
    val dockingTimeSeconds: Float = 0f,
    val batteryState: BatteryState = BatteryState.UNKNOWN,
    val batteryPercentage: Float = 0f,
    val isCharging: Boolean = false,
    val batteryVoltageVolts: Float = 0f,
    val batteryTemperatureCelsius: Float = 0f,
    val activeMap: String = "",
    val speedMps: Double = linearVelocityMps,
    val obstacleDistanceMeters: Double = nearestObstacleDistanceMeters?.toDouble() ?: 2.5,
    val isEmergencyStopped: Boolean = emergencyStopped,
    val internalTempCelsius: Double = batteryTemperatureCelsius.toDouble(),
    val batteryTempCelsius: Double = batteryTemperatureCelsius.toDouble(),
    val thermalState: ThermalState = ThermalState.NORMAL
)
