package com.alokrathava.sdk.model

enum class RobotCapability {
    NAVIGATION,
    MANUAL_CONTROL,
    DOCKING,
    SAFETY,
    TELEMETRY,
    BATTERY,
    HEALTH,
    MAP_SWITCHING,
    MAP_MANAGEMENT,
    VIRTUAL_WALLS,
    SAVED_LOCATIONS,
    WAYPOINT_NAVIGATION,
    MISSIONS,
    ROBOT_CONFIGURATION,
    ROBOT_DISCOVERY,
    DIAGNOSTICS,
    LOG_RETRIEVAL
}
